### ISSUE TITLE
Triggers Fatal Error on activation

### ISSUE THREAD

**Issue by bph** [kucrut/vite-for-wp-example-react#1]
Howdy, I wanted to see your demo... 
I tried to activate it and it came with a fatal error: 

`Warning: require_once(wp-content/plugins/**vite-for-wp-example-react-main/vendor/autoload.php): failed to open stream: No such file or directory** in wp-content/plugins/vite-for-wp-example-react-main/plugin.php on line 13`

1 | 0.0001 | 373304 | {main}( ) | .../plugins.php:0
2 | 0.1838 | 6169448 | plugin_sandbox_scrape( ) | .../plugins.php:192
3 | 0.1838 | 6169712 | include_once( 'wp-content/plugins/vite-for-wp-example-react-main/plugin.php' ) | .../plugin.php:2314

**Comment by kucrut** [comment]
Have you installed the composer dependencies? The `/vendor/autoload.php` should be created automatically when you run `composer install` from within the plugin directory.

**Comment by bph** [comment]
Ah that makes sense. 
You might need to change the order in your instructions. 

Make the second step "Activate the plugin from WordPress admin." the step after running the install commands.
