### ISSUE TITLE
[Vite] No manifest found in wp-content/plugins/js/dist.

### ISSUE THREAD

**Issue by salvobee** [kucrut/vite-for-wp-example-react#2]
After following instructions i'm getting this error in wordpress

when i render a page

The manifest.json file is in the corresponding directory, here is my plugin.php

```php
namespace Blabs\Dusty;

require_once __DIR__ . '/vendor/autoload.php';

use Kucrut\Vite;

/**
 * Frontend bootstrapper
 *
 * @return void
 */
function bootstrap(): void {
        add_action( 'wp_enqueue_scripts', __NAMESPACE__ . '\\enqueue_script' );
        add_action( 'wp_footer', __NAMESPACE__ . '\\render_app' );
}

/**
 * Render application's markup
 */
function render_app(): void {
        printf( '<div id="my-app" class="my-app"></div>' );
}

/**
 * Enqueue script
 */
function enqueue_script(): void {
        Vite\enqueue_asset(
                dirname( __DIR__ ) . '/js/dist',
                'js/src/main.tsx',
                [
                        'handle' => 'vite-for-wp-react',
                        'in-footer' => true,
                ]
        );
}

bootstrap();
```

looks like he is skipping the plugin name in path, the right path should be `wp-content/plugins/plugin-name/js/dist`

Any idea?

**Comment by salvobee** [comment]
Looks like i have to specify the path manually, like this:

`dirname( __DIR__ ) . '/my-plugin/js/dist/'`

Now it's working, even if i've noticed that i've to include `node_modules` directory in the bundle in order to works... is there any way to bundle everything needed in the dist/*.js files?

**Comment by kucrut** [comment]
I don't think you need to do that manually if you're following the file structure of this example plugin. Specifically, this plugin has the `frontend.php` file (that enqueues the script) inside the `inc/` directory.
